### ISSUE TITLE
Find_hyponyms doesn't find noun sequences of three or more noun sequences

### ISSUE THREAD

**Issue by MariyaIvanina** [mmichelsonIF/hearst_patterns_python#3]
Hi!

Thanks for this project. I'm using your project in the natural language processing task and it is very helpful.
I found one bug:
`sentence = re.sub(r"(NP_\w+ NP_\w+)+", lambda m: m.expand(r'\1').replace(" NP_", "_"), raw_sentence)`
this code helps only to merge 2 nouns in the sequence, but it doesn't work for sequences with 3 or more nouns. For example, in such sentence:

> 
There are such benefits as postharvest losses reduction, food increase and soil fertility improvement. 
> 
I should get such output [("postharvest losses reduction", "benefits"), ("food increase", "benefits"), ("soil fertility improvement", "benefits")]. But I get [("postharvest losses", "benefits"),("reduction", "benefits"), ("food increase", "benefits"), ("soil fertility", "benefits"), ("improvement", "benefits")].

I wrote function for this bug fix. May I contribute to your project?Thanks in advance.

**Comment by mmichelsonIF** [comment]
That would be great. Can you please make a pull request?

**Comment by MariyaIvanina** [comment]
I created a pull request. https://github.com/mmichelsonIF/hearst_patterns_python/pull/4
